### ISSUE TITLE
Remove mobile view tests for now

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-release-tests#97]
Right now we are skipping most, if not all, of the mobile view tests. We should enable these and make sure they're working still.

@AlexandraMoga would mobile view tests help softvision?

**Comment by AlexandraMoga** [comment]
@jrbenny35 currently, the AMO frontend used by Fenix is stripped of many of its functionalities, so, many of the UI tests will not work on mobile. I haven't removed the mobile view tests until now, since the direction for AMO on Fenix wasn't all that clear. 

What I would like to do at some point is create a test suite that is more adapted for android, to avoid skipping so many tests that are not relevant for mobile.

In the meantime, I think the following fixture should be updated to be specific for desktop tests only:

```
@pytest.fixture(
    scope='function',
    params=[DESKTOP, MOBILE],
    ids=['Resolution: 1920x1080', 'Resolution: 414x738'],
)
def selenium(selenium, request):
    """Fixture to set custom selenium parameters.

    This fixture will also parametrize all of the tests to run them on both a
    Desktop resolution and a mobile resolution.

    Desktop size: 1920x1080
    Mobile size: 738x414 (iPhone 7+)

    """
    # Skip mobile test with marker 'desktop_only'
    marker = request.node.get_closest_marker('desktop_only')
    if marker and request.param == MOBILE:
        pytest.skip('Skipping mobile test')
    selenium.set_window_size(*request.param)
    return selenium
```

**Comment by AlexandraMoga** [comment]
@jrbenny35 I was thinking to rewrite the fixture like this:

```
@pytest.fixture(
    scope='function',
    params=[DESKTOP],
    ids=['Resolution: 1920x1080'],
)
def selenium(selenium, request):
    """Fixture to set a custom resolution for tests running on Desktop."""

   selenium.set_window_size(*request.param)
   return selenium
```
I'd like to keep the 1920x1080 condition as the preferred resolution to run the tests on.

**Comment by jrbenny35** [comment]
I think that is a good idea, I will file another issue to track the work with mobile. I can take a look too, but I know you have more exposure to AMO.
